using System;
using System.Text.Json.Serialization;

namespace Deploy.Schema.Org
{
    /// <summary>
    /// A Report generated by governmental or non-governmental organization.
    /// </summary>
    public partial class Report : Article
    {
        public Report()
        {
            Type = "Report";
        }

    /// <summary>
    /// A Report generated by governmental or non-governmental organization.
    /// </summary>
        [JsonPropertyName("reportNumber")]
        public virtual string? ReportNumber { get; set; }

    }
}
